### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by zhalice2011** [ycjcl868/Express_Gulp#2]
![image](https://user-images.githubusercontent.com/24289349/28819016-6faaf768-76df-11e7-8b1a-63d663de8dc5.png)

**Comment by zhalice2011** [comment]
好吧接下来运行一下这个命令就可以了

npm install --save-dev jshint gulp-jshint

**Comment by ycjcl868** [comment]
[#7a2e019](https://github.com/ycjcl868/Express_Gulp/commit/7a2e0190dae3b13034b06af25f31d9ee4f235f66) fix the bug~
Thanks!
